const tableDefaultConfig = {
  tableEmptyMessage: undefined,
  tableLoadingMessage: undefined,
  pagination: true,
  paginationPageNeighbours: 1,
  paginationCurrentPage: 1,
  paginationNumberOfItemsToPage: 15,
  paginationTotalItems: undefined,
  filter: true,
  filterSelectedItemsCount: undefined,
  filterType: undefined,
  filterBodyTitle: undefined,
  search: true,
  searchPlaceholder: undefined,
  searchString: undefined,
  refresh: true,
  refreshCallback: undefined,
  contextMenu: true,
  readOnly: undefined,
  sortSortingValue: undefined,
  tableLoading: undefined,
  tableHeaderHeight: undefined,
  tableRowHeight: undefined,
  cellBordered: undefined,
  bordered: undefined,
};

export default tableDefaultConfig;
