export const callStatisticTable = [
  {
    id: 0,
    title: 'Номер очереди',
    value: 'QueuePhone',
    type: '',
    controls: [],
  },
  {
    id: 1,
    title: 'Дата начала',
    value: 'StartPeriod',
    type: 'date',
    controls: [],
  },
  {
    id: 2,
    title: 'Дата окончания',
    value: 'EndPeriod',
    type: 'date',
    controls: [],
  },
  {
    id: 3,
    title: 'Время расчета статистики',
    value: 'CalcTime',
    type: 'date',
    controls: [],
  },
  {
    id: 4,
    title: 'Контактность',
    value: 'CR',
    type: '',
    controls: [],
  },
  {
    id: 5,
    title: 'Средняя продолжительность переведённого звонка',
    value: 'AvgDurationTalk',
    type: '',
    controls: [],
  },
  {
    id: 6,
    title: 'Время между завершением соединения и статусом оператора "на линии/в работе"',
    value: 'AvgDurationUpdate',
    type: '',
    controls: [],
  },
  {
    id: 7,
    title: 'Среднее время набора 1 номера',
    value: 'AvgDurationDial',
    type: '',
    controls: [],
  },
];

export const operatorInfoTable = [
  {
    id: 0,
    title: 'QueuePhone',
    value: 'TitleBriefcase',
    type: '',
    controls: [],
  },
  {
    id: 1,
    title: 'Дата начала',
    value: 'StartDate',
    type: 'date',
    controls: [],
  },
  {
    id: 2,
    title: 'Дата окончания',
    value: 'EndDate',
    type: 'date',
    controls: [],
  },
  {
    id: 3,
    title: 'Дата начала',
    value: 'CallCount',
    type: 'date',
    controls: [],
  },
  {
    id: 4,
    title: 'Дата окончания',
    value: 'CallCountAtTime',
    type: 'date',
    controls: [],
  },
  {
    id: 5,
    title: 'Дата начала',
    value: 'SuccessConnected',
    type: 'date',
    controls: [],
  },
  {
    id: 6,
    title: 'Дата окончания',
    value: 'SuccessConnectedAtTime',
    type: 'date',
    controls: [],
  },
  {
    id: 7,
    title: 'Дата начала',
    value: 'DroptCall',
    type: 'date',
    controls: [],
  },
  {
    id: 8,
    title: 'Дата окончания',
    value: 'DroptCallAtTime',
    type: 'date',
    controls: [],
  },
];
